---
title: "Tidy Tuesday Transit Costs"
author: "Jeff Grayum"
date: "1/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries.
```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggthemes)
library(scales)
library(skimr)
#install.packages("countrycode")
library(countrycode)
library(glue)
```

Loading datasets.
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-01-05')

transit_cost <- tuesdata$transit_cost %>%
  mutate_at(vars(start_year, end_year, real_cost), as.numeric) %>%
  mutate(country_code = ifelse(country == "UK", "GB", country),
    country = countrycode(country_code, "iso2c",
                          "country.name"),
    tunnel_per = tunnel / length) %>%
  mutate(rr = ifelse(rr, "Railroad", "Not railroad"))
```

Exploring the data
```{r}
transit_cost %>%
  view()

skimr::skim(transit_cost)

transit_cost %>%
  group_by(start_year) %>%
  summarize(mean_cost = mean(cost_km_millions),
            mean_length = mean(length)) %>%
  ggplot(aes(start_year, mean_cost, size = mean_length)) +
  geom_point()
```


```{r}
transit_cost %>%
  count(country, sort = TRUE) 

transit_cost %>%
  count(city, country, sort = TRUE)

transit_cost %>%
  filter(country == "United States") %>%
  mutate(line = fct_reorder(line, year)) %>%
  ggplot(aes(xmin = start_year, xmax = end_year, y = line, 
             color = city, size = real_cost)) +
  geom_errorbarh(height = 0.2) +
  labs(x = "Year",
       y = "",
       title = "Transit projects in the United States",
       color = "City",
       size = "Cost") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

transit_cost %>%
  ggplot(aes(cost_km_millions)) +
  geom_histogram() +
  scale_x_continuous(labels = dollar) +
  labs(x = "Cost / KM (Millions of USD)",
       y = "",
       title = "Transit projects cost per kilometer (millions of USD") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

transit_cost %>%
  filter(country != "NA") %>%
  filter(!is.na(cost_km_millions),
         tunnel_per == 1) %>%
  mutate(country = fct_lump(country, 12)) %>%
  add_count(country) %>%
  mutate(country = glue("{ country } ( {n} )"), 
         country = fct_reorder(country, cost_km_millions)) %>%
  ggplot(aes(cost_km_millions, country, fill = rr)) +
  geom_boxplot() +
  scale_x_continuous(labels = dollar) +
  labs(x = "Cost / KM (Millions of USD)",
       y = "",
       title = "Transit projects cost per kilometer (millions of USD",
       fill = "") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

```


We have a lot of data on China, so let's start looking there!
```{r}
transit_cost %>%
  filter(country == "China",
         !is.na(cost_km_millions),
         tunnel_per == 1) %>%
  mutate(city = fct_lump(city, 12)) %>%
  add_count(city) %>%
  mutate(city = glue("{ city } ( {n} )"), 
         city = fct_reorder(city, cost_km_millions)) %>%
  ggplot(aes(cost_km_millions, city, fill = rr)) +
  geom_boxplot() +
  scale_x_continuous(labels = dollar) +
  expand_limits(x = 0) +
  labs(x = "Cost / KM (Millions of USD)",
       y = "",
       title = "Transit projects cost per kilometer (millions of USD) in Chinese cities",
       fill = "") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

transit_cost %>%
  filter(country == "China",
         !is.na(cost_km_millions),
         tunnel_per == 1) 

transit_cost %>%
  filter(country == "China",
         city == "Shanghai",
         !is.na(start_year),
         !is.na(end_year)) %>%
  mutate(line = fct_reorder(line, year)) %>%
  ggplot(aes(xmin = start_year, xmax = end_year, y = line, 
             size = real_cost)) +
  geom_errorbarh(height = 0.2) +
  labs(x = "Year",
       y = "",
       title = "Transit projects in China",
       size = "Cost") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

transit_cost %>%
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>%
  group_by(year = (year %/% 5) * 5) %>%  # groups things into 5 yr bins
  summarize(median_cost_km = median(cost_km_millions),
            n = n()) %>%
  ggplot(aes(year, median_cost_km)) +
  geom_line() +
  geom_point(aes(size = n)) +
  theme_fivethirtyeight() +
  labs(x = "",
       y = "Median cost / km",
       title = "Medain cost / km of transit project in China by year",
       size = "Number of projects") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

transit_cost %>%
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>%
  mutate(year = (year %/% 5) * 5, 
        city = fct_lump(city, 5)) %>%  
  ggplot(aes(year, cost_km_millions, group = year)) +
  geom_boxplot(outlier.size = -1) +
  geom_jitter(aes(color = city), height = 0, width = 1) +
  theme_fivethirtyeight() +
  labs(x = "",
       y = "Cost / km (Real USD, Millions)",
       title = "Cost distribution / km in China",
       color = "City") +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  expand_limits(y = 0)

transit_cost %>%
  filter(country == "China") %>%
  distinct(year, ppp_rate)

transit_cost %>%
  ggplot(aes(cost_km_millions, real_cost / length)) +
  geom_point()


transit_cost %>%
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>%
  ggplot(aes(stations)) +
  geom_histogram(bidwidth = 5)


transit_cost %>%
  filter(tunnel_per == 1,
         end_year <= 2020,
         country == "China") %>%
  ggplot(aes(length, stations)) +
  geom_point() +
  expand_limits(x = 0, y = 0)

  
 ```

